# Generated by Django 5.2.8 on 2025-12-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.newscategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='category_name',
            field=models.CharField(max_length=32, verbose_name='Название категории'),
        ),
    ]
