# Generated by Django 5.2.8 on 2025-12-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_news_options_alter_newscategory_options_and_more'),
        ('index', '0004_seed_highlighted_news'),
    ]

    operations = [
    ]
