# Generated by Django 5.2.8 on 2025-12-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_merge_20251205_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
